### ISSUE TITLE
Save State Problem

### ISSUE THREAD

**Issue by guizot** [furkanaskin/TrickyNavigationSample#2]
Can you elaborate how to save state using Event.kt and EventObserver.kt ?
How to passing id to all views?

**Comment by nuhkoca** [comment]
@furkanaskin fyi

**Comment by furkanaskin** [comment]
Hi @guizot ,

You can read this blog : [Medium](https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150)

Also you can check this discussion : [EventObserver.kt](https://gist.github.com/JoseAlcerreca/e0bba240d9b3cffa258777f12e5c0ae9)

**Comment by furkanaskin** [comment]
@guizot , also you shouldn't give id to your all views. For example if you give id to your scrollView, it will save/restore own view state but if you not give an id to scrollView, it will lost their state on replace. With this situation you must give id to your scrollviews, recyclerviews, root views etc.
