### ISSUE TITLE
Save State Issue with BottomNavigation item click Listener

### ISSUE THREAD

**Issue by nawinkhatiwada** [furkanaskin/TrickyNavigationSample#3]
Save state does not work when the bottom navigation item is clicked.

How to replicate:
Steps: 

1. Go to search Fragment
2. type something on edit text
3. click the notification icon
4. click the search icon

Save state only works when pressing the back button

**Comment by furkanaskin** [comment]
Hi @nawinkhatiwada , the main idea on this project is faking multiple back stack. It just works for back press. When you click on a menu item, navigation every time creates new instance of a fragment.

I think you must use this behaviour : [Navigation Advanced Sample](https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample)

**Comment by nawinkhatiwada** [comment]
thanks
