### ISSUE TITLE
how to incorporate same things with advance navigation sample ?

### ISSUE THREAD

**Issue by vivekpanchal** [furkanaskin/TrickyNavigationSample#6]
I have implemented bottom navigation using an advanced navigation sample with multiple navigations graphs.
can you tell me how to incorporate the same Instagram like a stack with that ??

I have followed this example -> https://github.com/android/architecture-components-samples/tree/main/NavigationAdvancedSample

**Comment by furkanaskin** [comment]
Hi @vivekpanchal,

As i mentioned before this solution works with single graph. Maybe, [you can try this one](https://gist.github.com/iammert/47a89ed68dcf6e7cf32ac46b1d6265d6) instead of using NavigationAdvancedSample
